image_speed = 0
grav = 0
hsp = 0
vsp = 0
grounded = false
image_speed = 0
alarm[0] = 50
alarm[1] = 10
alarm[2] = alarm[1] - 75
global.panic.active = false
global.combo.timer = 0
global.combo.count = 0
